services:
  php:
    container_name: sisrancho-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - sisrancho-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: sisrancho
      MYSQL_USER: sti
      MYSQL_PASSWORD: password
  db:
    container_name: sisrancho-db
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sisrancho
      MYSQL_USER: sti
      MYSQL_PASSWORD: password
    networks:
      - sisrancho-network

  phpmyadmin:
    container_name: sisrancho-admin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sisrancho-network

  backup:
    container_name: sisrancho-backup
    image: appropriate/curl
    depends_on:
      - db
    volumes:
      - ./backups:/backups  # Pasta local onde os backups serão armazenados
    entrypoint: ["/bin/sh", "-c", "echo '0 0 * * * mysqldump -h db -u root -ppassword sisrancho > /backups/sisrancho-$(date +\\%F).sql' | crontab - && crond -f"]
    networks:
      - sisrancho-network

networks:
  sisrancho-network:

volumes:
  db_data:
